2022-08-04T05:12:12.398Z | [  [31merror[39m  ] | databse is not connected
2022-08-04T05:12:12.399Z | [  [31merror[39m  ] | bad auth : Authentication failed.
